sources:
    - name: uniswapv3Polygon
      handler:
          graphql:
              endpoint: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon

documents:
    - ./src/graphql/queries.ts
